---
title: "Webscraping data on Soviet secret police leaders"
author: "Martin Kosík"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(magrittr)
library(tidyverse)
library(stringr)
library(stringi)
Sys.setlocale("LC_CTYPE", "russian") 

```

## Period from 1934 to 1941
```{r}
memo_site <- "http://old.memo.ru/history/nkvd/kto/biogr/index.htm"


iframe <- html_session("http://old.memo.ru/history/nkvd/kto/biogr/index.htm")%>% 
  html_nodes(xpath = "//html//frameset//frame") %>% 
  magrittr::extract2(3) %>% 
  html_attr("src") 

number_of_leaders = 572

all_iframes <- str_c("gb", 1:number_of_leaders, ".htm")

get_htmls <- function(iframe, memo_site = "http://old.memo.ru/history/nkvd/kto/biogr/") {
  html_session(str_c(memo_site, iframe)) %>%
    html_nodes("body > div > p")
}

all_htmls <- all_iframes %>% 
  map(get_htmls)

all_texts <- all_htmls %>% 
  map(html_text)

```

Extract information from the text
```{r}
nkvd_leaders_pre_war <- tibble(.rows = number_of_leaders)
```

## Period from 1941 to 1954
Download the data and convert them to text
```{r}
memo_site <- "http://old.memo.ru/history/nkvd/kto2/"


iframe <- html_session("http://old.memo.ru/history/nkvd/kto2/")%>% 
  html_nodes(xpath = "//html//frameset//frame") %>% 
  magrittr::extract2(3) %>% 
  html_attr("src") 

number_of_leaders = 1308

all_iframes <- str_c("kto_2-", str_pad(1:number_of_leaders, 4, pad = "0"), ".html")


all_htmls <- all_iframes %>% 
  map(get_htmls, memo_site = "http://old.memo.ru/history/nkvd/kto2/")

all_texts <- all_htmls %>% 
  map(html_text)

```

Extract information from the text
```{r}

nkvd_leaders <- tibble(.rows = number_of_leaders)
  
nkvd_leaders$full_name <- all_texts %>% 
  map_chr(1)


nkvd_leaders$birth_year <- all_texts %>% 
  map_chr(2) %>% 
  map(str_extract_all, pattern = "[:digit:]{4}") %>% 
  map(1) %>% 
  map(1) %>% 
  map(as.integer)

nkvd_leaders$birth_year <- as.integer(nkvd_leaders$birth_year)


nkvd_leaders$death_year <- all_texts %>% 
  map_chr(2) %>% 
  map(str_extract_all, pattern = "[:digit:]{4}") %>% 
  map(1) %>% 
  map(2) %>% 
  map(as.integer)

nkvd_leaders$death_year <- as.integer(nkvd_leaders$death_year)


#all_texts %>% 
#  map_chr(2) %>% 
#  gsub("^\\(.+, (.+) - .* \\)\\.$", "\\1", .)
  


communist_party_entrance_date <- all_texts %>% 
  map_chr(3) %>% 
  gsub("^.*(В|Член) КП ?с?( |\\.)(\\d{2}\\.\\d{2})\\.?.*$", "\\3", .) %>% 
  str_split(pattern = "\\.", n = 2)

nkvd_leaders$party_entrance_year <- communist_party_entrance_date %>% 
  map(2) %>% 
  map(~ str_c("19", .)) %>% 
  map(as.numeric)

nkvd_leaders$party_entrance_year <- as.numeric(nkvd_leaders$party_entrance_year)


nkvd_leaders$party_entrance_month <- communist_party_entrance_date %>% 
  map(1) %>% 
  map(as.numeric)

nkvd_leaders$party_entrance_month <- as.numeric(nkvd_leaders$party_entrance_month)


nkvd_leaders$ethnicity <-all_texts %>% 
  map_chr(3) %>% 
  gsub("^Родился в семье (.+?)\\. (.+?)\\. .*$", "\\2", ., perl = TRUE) # %>%  map(as.factor)

nkvd_leaders %>%
  count(ethnicity, sort = T) 


write_csv(nkvd_leaders, "nkvd_leaders_1941_to_1954.csv")


#all_texts %>% 
#  map_chr(3) %>% 
#  sub("^Родился в семье (.+?)\\. ", "\\2", ., perl = TRUE) 


#all_texts %>% 
#  map_chr(3) %>% 
#  sub("^Родился в семье ((.+?)(?=\\. ))", "\\1", ., perl = TRUE)

```


PDF file reading
```{r}
#library(pdftools)
#library(tabulizer)
#library(here)
library(tidyverse)
```

```{r eval=FALSE}
download.file("http://old.memo.ru/uploads/files/845.pdf", "soviet_secret_police_1941_to_1954.pdf", mode = "wb")

txt <- pdf_text("soviet_secret_police_1941_to_1954.pdf")

fonts <- pdf_fonts("soviet_secret_police_1941_to_1954.pdf")


out1 <- extract_tables("soviet_secret_police_1941_to_1954.pdf", pages = 80, guess = FALSE, output = "data.frame",
                       encoding = "UTF-8")
str(out1)


table_data <- extract_areas("soviet_secret_police_1941_to_1954.pdf", pages = 80, output = "data.frame",
              encoding = "UTF-8")


text = txt[[80]] %>% 
  str_sub(start = 88+1)

src <- ""
trim <- function (x) gsub("^\\s+|\\s+$", "", x)


result <- ''
QTD_COLUMNS = 2
lstops <- gregexpr(pattern =" ", txt[[80]])
stops <- as.integer(names(sort(table(unlist(lstops)),decreasing=TRUE)[1:2]))


for(i in seq(1, QTD_COLUMNS, by=1))
  {
    temp_result <- sapply(text, function(x){
      start <- 1
      stop <-stops[i] 
      if(i > 1)            
        start <- stops[i-1] + 1
      if(i == QTD_COLUMNS)#last column, read until end.
        stop <- nchar(x)+1
      substr(x, start=start, stop=stop)
    }, USE.NAMES=FALSE)
    temp_result <- trim(temp_result)
    result <- append(result, temp_result)
  }
  result



txt[[80]] %>% 
  str_remove("\\A([^\\r\\n]*\\n)") %>% 
 # str_remove(pattern = "                             Руководители органов НКГБ–НКВД–МГБ–МВД СССР 1941–1954\r\n80\r\n") %>% 
  cat()

  
txt[[80]] %>% 
  str_sub(
    start = nchar("                             Руководители органов НКГБ–НКВД–МГБ–МВД СССР 1941–1954\r\n80\r\n") + 1) %>% 
  #str_trim() %>% 
  cat()
  
out1 <- extract_tables(txt[[80]])


nchar("                             Руководители органов НКГБ–НКВД–МГБ–МВД СССР 1941–1954\r\n80\r\n")
```





